name: Upload project to PyPI

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: pip

      - run: pip install -r requirements.txt

      - run: py -m build

      - name: Upload the artifacts
        uses: actions/upload-artifact@v7
        with:
          path: dist/
